### ISSUE TITLE
what is wrong with angular weekly

### ISSUE THREAD

**Issue by myzhibie** [jexia/jexia-sdk-js#156]
I am one of the fans of angular  weekly. but it is broken and unavaliable. what is wrong with it

**Comment by rafaelakopian** [comment]
Hi there, Thanks for your question and support! 
Because of the current situation "corona", we are all work a bit different and that is the reason why we didn't manage to send the newsletters. Please give us a bit more time and we will come with the new editions. Thanks!

**Comment by myzhibie** [comment]
Thanks for your reply. I 'm looking forward for your recoveration
