### ISSUE TITLE
Warnings on a Quasar build

### ISSUE THREAD

**Issue by Berkmann18** [jexia/jexia-sdk-js#169]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behaviour
Getting the following warnings when running `quasar d`:
```
 WARNING  Compiled with 2 warnings                                                                                                                                                15:32:25

 warning  in ./node_modules/ws/lib/BufferUtil.js

Module not found: Error: Can't resolve 'bufferutil' in '/home/maxie/Projects/price-calc/node_modules/ws/lib'

 warning  in ./node_modules/ws/lib/Validation.js

Module not found: Error: Can't resolve 'utf-8-validate' in '/home/maxie/Projects/price-calc/node_modules/ws/lib'

ℹ ｢wds｣: Project is running at http://0.0.0.0:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: 404s will fallback to /index.html
 App · Opening default browser at http://localhost:8080/
```

## Expected behaviour

No warnings.

## Minimal reproduction of the problem with instructions

```shell
npm jexia-sdk-js --save
quasar d
```

## What is the motivation / use case for changing the behaviour?
N/A

## Please tell us about your environment

<pre><code>
SDK version: 5.1.0

Execution Platform Error:

- [x] NodeJS version 12.6.0
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Operation System:

ArchLinux 5.6.15

Others:

Quasar: v1.12.3
</code></pre>
Repo: https://github.com/Berkmann18/price-calc

**Comment by marlosin** [comment]
Hi @Berkmann18 sorry for the delayed response. can you share the logs you got or even a working example of that application?

**Comment by Berkmann18** [comment]
@marlosin I've added the logs and a link to the [repo](https://github.com/Berkmann18/price-calc).

**Comment by marlosin** [comment]
@Berkmann18 I couldn't reproduce the issue. I cloned your repo, installed sdk and executed `npm run develop`, no warning is thrown. By your logs I can see that the warnings are related to `ws` lib. If you're using sdk in the browser you don't need to install it.

**Comment by Berkmann18** [comment]
@marlosin Those logs actually started showing up before I even had `ws` as a dependency (which I installed based on https://github.com/jexia/jexia-vue-todo, an example Una V gave me).

**Comment by marlosin** [comment]
> @marlosin Those logs actually started showing up before I even had `ws` as a dependency (which I installed based on https://github.com/jexia/jexia-vue-todo, an example Una V gave me).
> 
> And also, I did remove it since and still get the warning.

Could you create a branch and push this code that is raising the warning, so I can investigate?

**Comment by Berkmann18** [comment]
@marlosin Have you checked the [`dev` branch](https://github.com/Berkmann18/price-calc/tree/dev)?

**Comment by marlosin** [comment]
do you use server side rendering on this app? If no, just replace the import `jexia-sdk-js/node` by `jexia-sdk-js/browser` and no warnings would be thrown. also you can upgrade the version to the latest: `5.3.0`. Anyway our `ws` is a bit outdated, so I'll run some tests to upgrade it, thanks!

**Comment by Berkmann18** [comment]
> do you use server side rendering on this app?

No, mostly as a PWA.

> just replace the import `jexia-sdk-js/node` by `jexia-sdk-js/browser` and no warnings would be thrown. you can also upgrade the version to the latest one: `5.3.0`

That solved the issue, now time to sort this CORS problem app.jexia.com/auth is giving me.

**Comment by marlosin** [comment]
> > do you use server side rendering on this app?
> 
> No, mostly as a PWA.
> 
> > just replace the import `jexia-sdk-js/node` by `jexia-sdk-js/browser` and no warnings would be thrown. you can also upgrade the version to the latest one: `5.3.0`
> 
> That solved the issue, now time to sort this CORS problem app.jexia.com/auth is giving me.

that's weird, you can check it out in your response headers from this endpoint that we include `access-control-allow-origin: *` so it really shouldn't happen. if you want to have a chat about it you can go to our [discord](https://chat.jexia.com/) on #sdk channel

**Comment by Berkmann18** [comment]
> that's weird, you can check it out in your response headers from this endpoint that we include access-control-allow-origin: * so it really shouldn't happen. if you want to have a chat about it you can go to our discord on #sdk channel

It ended up working when I rectified the environment variables and adding missing fields that weren't in the example I used but that were required for it to work.
