### ISSUE TITLE
If I want to pass a boolean value into isEqualTo() it results in an error in Typescript, because isEqualTo() expects an argument of type string

### ISSUE THREAD

**Issue by nandekonst** [jexia/jexia-sdk-js#22]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report
[x ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
In Typescript, passing in a `boolean` value into `isEqualTo()` results in an error

## Expected behavior
I feel `isEqualTo()` should be able to handle a `boolean` value. Now I have to cast my `boolean` into a `string` before passing it, and do something like this ..... `    let vaccinatedasString = vaccinated? "true":"false";`  This feels a bit like a shortcoming

## Minimal reproduction of the problem with instructions
-This occures when using `fieldFiltering` 

## What is the motivation / use case for changing the behavior?
I have a usecase where I want to compare `boolean` without casting it to `string` first. 

## Please tell us about your environment
Angular: V6
TS version: 2.7.2

**Comment by KutsenkoA** [comment]
There is a bunch of conditional methods supported by SDK at the moment. They all understand only `string` values (except `isNull` and `isNotNull` which take nothing). Here is a full list:

* isGreaterThan
* isLessThan
* isEqualTo
* isDifferentFrom
* isEqualOrGreaterThan
* isEqualOrLessThan
* isNull
* isNotNull
* isInArray
* isNotInArray
* isLike
* satisfiesRegexp
* isBetween

I think it would be nice if all these methods could take all supported field types. For typescript users we can add generic type to give a hint which exactly type is allowed. 

The mapping for dataset field types could be like this:

dataset field type | Typescript type
------------------ | ----------
int8 | number
float8 | number
timestamptz | Date
date | Date
bool | boolean
varchar | string
jsonb | object
uuid | string (custom UUID type for typescript)

**Comment by nandekonst** [comment]
This would be a very nice solution I think. It would make these methods a lot more flexible!
