### ISSUE TITLE
Multiple where conditions can be chained but only the last condition is executed.

### ISSUE THREAD

**Issue by nandekonst** [jexia/jexia-sdk-js#27]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report
[x] Feature request
[x] Documentation issue or request
</code></pre>

## Current behavior
My usecase is that I want to create an Angular view that contains 3 filters which enables me to filter a Cats datasets on"
- color OR
- race OR
- vaccinated (true/false)

I checked the SDK documentation on this matter and I find that Filtering conditions can be nested at any level. In my case I would have to create a flat filter like this:

`let flatFilter = field("color").isEqualTo(cat.color)
                 .or( field("race").isEqualTo(cat.race))
                 .or( field("vaccinated").isEqualTo(cat.vaccinated));`

I start testing the filtering conditions first seperately and can conclude that seperately they work in my service and that the expected results are delivered in the console

`RECORDS[{"id":"a2954f28-0db2-423e-be01-d661c0534d92","created_at":"2018-06-07T13:46:24.766475Z","updated_at":null,"name":"Lester","color":"black","race":"Siamese","vaccinated":false,"shelters_id":"d24e8e7d-920a-46da-b41e-c51786053499","date_of_birth":"2017-01-08T23:00:00Z"},{"id":"c577ca85-266a-4b10-8d9e-d54b76c0d4bf","created_at":"2018-07-05T09:06:23.748663Z","updated_at":null,"name":"Axl Rose","color":"black","race":"Siamese","vaccinated":true,"shelters_id":"53b542a1-e4ff-4235-a345-c11e3f4689f1","date_of_birth":"2018-07-23T22:00:00Z"}]`

Next, I test them as a chained flat filter:

`return this.catDataset.select().where(flatFilter).execute();`

But now, only the filter is applied correctly on the last condition (vaccinated). The first 2 conditions give back the wrong info, which I cannot really see a pattern in. When testing the chained filter and wanting to filter on color="black" the result is:

`RECORDS[{"id":"2bee5d90-0381-417d-a7df-56531487a612","created_at":"2018-06-05T15:05:59.356044Z","updated_at":null,"name":"Beppi","color":"red","race":"European","vaccinated":false,"shelters_id":"688a5925-60d3-469e-8ca5-d1c9f6268f14","date_of_birth":"2018-07-23T22:00:00Z","sheltername":"The Catshouse"},{"id":"a2954f28-0db2-423e-be01-d661c0534d92","created_at":"2018-06-07T13:46:24.766475Z","updated_at":null,"name":"Lester","color":"black","race":"Siamese","vaccinated":false,"shelters_id":"d24e8e7d-920a-46da-b41e-c51786053499","date_of_birth":"2017-01-08T23:00:00Z"},{"id":"c577ca85-266a-4b10-8d9e-d54b76c0d4bf","created_at":"2018-07-05T09:06:23.748663Z","updated_at":null,"name":"Axl Rose","color":"black","race":"Siamese","vaccinated":true,"shelters_id":"53b542a1-e4ff-4235-a345-c11e3f4689f1","date_of_birth":"2018-07-23T22:00:00Z"}]`

I get back the 2 records with color: black, but also one with color: red.  The records with color: white are not displayed. 

When I returned to the documentation, I read the following sentence:

`Multiple .where calls can be chained, but only the last call will be taken into account. If a complex condition needs to be set for filtering, it has to be created in one go (in-line or not) and passed as an argument to the .where method.`

This is indeed the exact behavior that I experience, but I would expect to be able to filter on or color, or race or vaccinated. And that all of them would be executed correctly independently of one another, although chained. So at the moment, I feel that basically the documentation is just stating that chaining multiple conditions is not working.  

## Expected behavior
You should be able to chain filtering conditions using `.or` operator. All these filtering should return the correct filtered data, and not only apply correctly to the last condition. 

## Minimal reproduction of the problem with instructions
You can see this behavior also in action creating flat filter conditions and execute in Node.

## Please tell us about your environment
Angular: V6
TS version: 2.7.2
SDK version: 3.3.1
ng-jexia: 1.1.3

**Comment by KutsenkoA** [comment]
The problem here is `isEqualTo(null)` operator for the field with type `boolean`. In this case, the dataset automatically casts this to `isEqualTo(false)` which ends up with "wrong" results. 

  There are methods `isNull()` and `isNotNull()` for the comaprison with `null`.
