### ISSUE TITLE
Miss type in documetation

### ISSUE THREAD

**Issue by belokonm** [jexia/jexia-sdk-js#3]
Paragraph : **The Module system**
Path : jexia-sdk-js/extra_docs/quickstart.md 

Curent: 
dataModule.dataset("posts")
  .select()
  .then( (data) => {....
   
Change to: 
dataModule.dataset("posts")
  .select()**.execute()**
  .then( (data) => {....

**Comment by willgm** [comment]
Thanks man! :+1:

**Comment by belokonm** [comment]
Thx Bill.
I will check asap.
Congrats with release :)

2018-05-10 22:09 GMT+02:00 William Grasel <notifications@github.com>:
