### ISSUE TITLE
npm: sdk removes dependencis from project folder  

### ISSUE THREAD

**Issue by belokonm** [jexia/jexia-sdk-js#4]
>create-react-app my_app
>cd my_app
>npm start  --- good result
> Ctrl+C / Y
> npm install jexia-sdk-js --save
+ jexia-sdk-js@3.2.0
added 3 packages and removed 1224 packages in 66.659s
> npm start 
Error: 'react-scripts' is not recognized as an internal or external command,

To fix it you need to run **npm install** again

**Comment by willgm** [comment]
I follow the steps and couldn't reproduce the error. Did you test with the latest version of the SDK and `creat-react-app`?

I published an example project with the result of my tests, you can check it out here:
https://github.com/willgm/react-jexia-example

Can you give more information about the issue if it persist?
