### ISSUE TITLE
Fields function should also receive an array as parameter

### ISSUE THREAD

**Issue by musghost** [jexia/jexia-sdk-js#8]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

The `field` method is currently built to accept parameter like:

```
[..]
posts.select().fields("id", "title").execute().then( (records) => {
  // the individual record objects will only have the two properties defined above
});
[..]
```

## What is the motivation / use case for changing the behavior?

I can take advantage of `apply` but this argument is confusing and is also wrapped in the object.

The method `fields` should also accept an array like this example:

```
[..]
posts.select().fields(["id", "title"]).execute().then( (records) => {
  // the individual record objects will only have the two properties defined above
});
[..]
```

**Comment by willgm** [comment]
What if the use use the spread operator of the ES6/ES2016?

```js
[..]
posts.select().fields(...["id", "title"]).execute().then( (records) => {
  // the individual record objects will only have the two properties defined above
});
[..]
```

**Comment by belokonm** [comment]
Did a test.  Working well. 
Thx guys!
